version: '3'
services:
  frontend:
    image: alex13slem/time-app-frontend-dev
    restart: always
    ports:
      - '3000:3000'

  api:
    image: alex13slem/time-app-api-dev
    restart: always
    ports:
      - '5555:5000'
    # После какого контейнера создастся данный контейнер
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST = 'mysql'
      - MYSQL_USER = 'root'
      - MYSQL_PORT = '3306'
      - MYSQL_PASSWORD = 'password'
      - MYSQL_DB = 'time_db'
      
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: time_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data_pub:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  mysql_data_pub:
