version: '3'
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./src:/srv/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laratest_db
      MYSQL_USER: laratest
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build: .
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - '9000:9000'
    networks:
      - laravel
